#!/bin/bash
#
# Prepares the "stack" to run apps and the environment to run buildpacks
#

echo 'deb http://us.archive.ubuntu.com/ubuntu/ saucy-updates multiverse' >> /etc/apt/sources.list
echo 'deb-src http://us.archive.ubuntu.com/ubuntu/ saucy-updates multiverse' >> /etc/apt/sources.list
echo 'deb http://archive.ubuntu.com/ubuntu saucy main restricted universe multiverse' >> /etc/apt/sources.list

#
# SYSTEM PACKAGES
#
apt-get update
xargs apt-get install -y --force-yes < /build/packages.txt
apt-get clean

#
# SUPPORTED BUILDPACKS
#
mkdir -p /build/buildpacks
cd /build/buildpacks
xargs -L 1 git clone --depth=1 < /build/buildpacks.txt

#
# MISC
#

# Ruby buildpack system configuration
update-alternatives --set ruby /usr/bin/ruby1.9.1
update-alternatives --set gem /usr/bin/gem1.9.1
gem install bundler

# GLFW3 built from source
GLFW3_URL="https://github.com/glfw/glfw/archive/3.0.4.tar.gz"
curl -L --silent $GLFW3_URL | tar xzf - -C /build
cd /build/glfw-3.0.4
mkdir -p build
cd build
cmake .. -DBUILD_SHARED_LIBS=on
make
make install
