#!/bin/bash
#
# Prepares the "stack" to run apps and the environment to run buildpacks
#

echo 'deb http://us.archive.ubuntu.com/ubuntu/ saucy-updates multiverse' >> /etc/apt/sources.list
echo 'deb-src http://us.archive.ubuntu.com/ubuntu/ saucy-updates multiverse' >> /etc/apt/sources.list
echo 'deb http://archive.ubuntu.com/ubuntu saucy main restricted universe multiverse' >> /etc/apt/sources.list

#
# SYSTEM PACKAGES
#
apt-get update
apt-get remove -y x264 libx264-dev
xargs apt-get install -y --force-yes < /build/packages.txt
apt-get clean

#
# SUPPORTED BUILDPACKS
#
mkdir -p /build/buildpacks
cd /build/buildpacks
xargs -L 1 git clone --depth=1 < /build/buildpacks.txt

#
# MISC
#

# Ruby buildpack system configuration
update-alternatives --set ruby /usr/bin/ruby1.9.1
update-alternatives --set gem /usr/bin/gem1.9.1
gem install bundler

# GLFW3 built from source
GLFW3_URL="https://github.com/glfw/glfw/archive/3.0.4.tar.gz"
curl -L --silent $GLFW3_URL | tar xzf - -C /build
cd /build/glfw-3.0.4
mkdir -p build
cd build
cmake .. -DBUILD_SHARED_LIBS=on
make
make install

mkdir -p ~/ffmpeg_sources
mkdir -p ~/ffmpeg_build

cd ~/ffmpeg_sources
wget http://download.videolan.org/pub/x264/snapshots/last_x264.tar.bz2
tar xjvf last_x264.tar.bz2
cd x264-snapshot*
./configure --prefix="$HOME/ffmpeg_build" --bindir="$HOME/bin" --enable-static
make -j8
make install
make distclean

cd ~/ffmpeg_sources
wget http://webm.googlecode.com/files/libvpx-v1.3.0.tar.bz2
tar xjvf libvpx-v1.3.0.tar.bz2
cd libvpx-v1.3.0
./configure --prefix="$HOME/ffmpeg_build" --disable-examples
make -j8
make install
make clean

cd ~/ffmpeg_sources
wget http://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2
tar xjvf ffmpeg-snapshot.tar.bz2
cd ffmpeg
PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig"
export PKG_CONFIG_PATH
./configure --prefix="$HOME/ffmpeg_build" --extra-cflags="-I$HOME/ffmpeg_build/include" \
   --extra-ldflags="-L$HOME/ffmpeg_build/lib" --bindir="$HOME/bin" --extra-libs="-ldl" --enable-gpl \
   --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopus \
   --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree --enable-x11grab
make -j8
make install
make distclean
hash -r

mkdir -p ~/glew_sources

cd ~/glew_sources
wget https://sourceforge.net/projects/glew/files/glew/1.10.0/glew-1.10.0.tgz/download
tar -xzvf download
cd glew-1.10.0
make -j8
make install
make clean
hash -r 

echo '/usr/lib64/' >> /etc/ld.so.conf
ldconfig
